### ISSUE TITLE
Nancy not picking up my custom JsonSerializer

### ISSUE THREAD

**Issue by cvetomirtodorov** [NancyFx/Nancy.Serialization.JsonNet#23]
I followed the `readme.md` instructions after creating my custom `JsonSerializer` in order to register it. But it wasn't picked up. I had to add the following lines to make it work:

```C#
container.Register<ISerializer, JsonNetSerializer>();
container.Register<IBodyDeserializer, JsonNetBodyDeserializer>();
```

Is the documentation incomplete/inaccurate or have I missed something? It clearly states that Nancy should detect `JsonNetSerializer` and `JsonNetBodyDeserializer` but it fails to do so.

**Comment by cvetomirtodorov** [comment]
I suppose that would be an issue of the compiler optimizations and lack of hard reference. Closing it.

**Comment by khellang** [comment]
Yeah. That's an unfortunate consequence of assembly scanning. We recently added the [`IncludeInNancyAssemblyScanning`](https://github.com/NancyFx/Nancy/wiki/Bootstrapper#finding-the-right-bootstrapper) attribute to help with this.
