### ISSUE TITLE
v2.0.0 to use Json.NET v9?

### ISSUE THREAD

**Issue by RTodorov** [NancyFx/Nancy.Serialization.JsonNet#43]
Hi guys,

Do you have any intentions to update v2 to use netcoreapp1.0 and Json.Net 9.0.1?

I had to add net452 as a dependency to my project just because of Nancy.Serialization.JsonNet and it conflicted with Json.Net 9 package I'm using...

Thank you!

**Comment by Sphiecoh** [comment]
Addressed by [pull request #51](https://github.com/NancyFx/Nancy.Serialization.JsonNet/pull/51)

**Comment by jchannon** [comment]
2.0.0-clinteastwood will have this in which should be very soon
