### ISSUE TITLE
Custom serializer doesn't run

### ISSUE THREAD

**Issue by sakopov** [NancyFx/Nancy.Serialization.JsonNet#55]
```
    public sealed class CustomJsonSerializer : JsonSerializer
    {
        public CustomJsonSerializer()
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver();
            NullValueHandling = NullValueHandling.Ignore;
            DefaultValueHandling = DefaultValueHandling.Ignore;
        }
    }
```

```
    public class CustomApiBootstrapper : DefaultNancyBootstrapper
    {
        protected override void ConfigureRequestContainer(TinyIoCContainer container, NancyContext context)
        {
            base.ConfigureRequestContainer(container, context);

            container.Register<JsonSerializer, CustomJsonSerializer>();
        }
    }
```

The `CustomJsonSerializer` constructor never executes. The JSON response still has null properties.

```
{
  "data": {
    "application": "myApp",
    "version": "1.0",
    "links": {
      "self": {
        "href": "/api"
      }
    }
  },
  "message": null,
  "status": "success"
}
```

What's missing?

**Comment by thecodejunkie** [comment]
Nancy consumes 'ISerializer' instances. You need to implement that in order for Nancy to discover and use it

**Comment by sakopov** [comment]
That breaks it even more. 

Added to bootstrap.

```
container.Register<ISerializer, JsonNetSerializer>();
container.Register<JsonSerializer, MonitrJsonSerializer>();
```

The JSON looks like:

```
{
  "Data": {
    "Application": "myApp",
    "Version": "1.0",
    "Links": {
      "self": {
        "Href": "/api"
      }
    }
  },
  "Message": null,
  "Status": "success"
}
```

**Comment by sakopov** [comment]
It seems like i'm having problems with everything that Nancy is supposed to magically pick up and run. (i.e. I'm using FluentValidation with Nancy which also had the same problem until i explicitly added it to dependency registration). So this makes me wonder if the problem is in how i'm running Nancy? I'm using Topshelf.Nancy to host it in a windows service.

**Comment by ryanulit** [comment]
@sakopov that registration is literally the ONLY way it will work for me using the `Nancy.Bootstrappers.Autofac` bootstrapper on a 64 bit windows machine.  Thank you.

**Comment by fryette** [comment]
The same problem for ASP.NET Core 2.0
`
        protected override void ConfigureApplicationContainer(TinyIoCContainer container)
        {
            base.ConfigureApplicationContainer(container);

            container.Register<JsonSerializer, CustomJsonSerializer>();
        }

        public sealed class CustomJsonSerializer : JsonSerializer
        {
            public CustomJsonSerializer()
            {
                this.DateFormatString = "yyyy-MM-dd";
            }
        }
    }`

My Module
`return Negotiate.WithModel(new {Birthday = DateTime.Now).WithHeader("cache-control", "max-age:86400");`

With that I have results

> "1978-04-28T00:00:00.0000000+03:00"

My serializer never initialized

**Comment by YuriGal** [comment]
@ryanulit  I know it's been a while but could you please show an example 
 how custom JsonSerializer is configured in `Nancy.Bootstrappers.Autofac` bootstrapper ?

**Comment by ryanulit** [comment]
@YuriGal here's what worked for me, but this is 2+ years old so there may be a better way now:

```
public class ApiBootstrapper : AutofacNancyBootstrapper
{
    protected override void ConfigureApplicationContainer(ILifetimeScope existingContainer)
    {
        base.ConfigureApplicationContainer(existingContainer);

        existingContainer.Update(builder =>
        {
            builder.RegisterType<JsonNetSerializer>().As<ISerializer>();
            builder.RegisterType<JsonNetBodyDeserializer>().As<IBodyDeserializer>();
            builder.RegisterType<CustomJsonSerializer>().As<JsonSerializer>();
        });
    }
}
```

And the CustomJsonSerializer class:
```
public class CustomJsonSerializer : JsonSerializer
{
    public CustomJsonSerializer()
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver();
        NullValueHandling = NullValueHandling.Ignore;
        Converters.Add(new StringEnumConverter(true));
    }
}
```

And here's my packages.config for version references:

```
<package id="Nancy" version="1.4.5" targetFramework="net471" />
<package id="Nancy.Bootstrappers.Autofac" version="1.4.1" targetFramework="net471" />
<package id="Nancy.Serialization.JsonNet" version="1.4.1" targetFramework="net471" />
<package id="Newtonsoft.Json" version="12.0.2" targetFramework="net471" />
```

**Comment by YuriGal** [comment]
@ryanulit Thank you so much for the prompt response! I figured it as far as `builder.RegisterType( )` but was missing the `.As( )` part. Thanks again!
