### ISSUE TITLE
Add support for .NET Standard

### ISSUE THREAD

**Issue by cocowalla** [NancyFx/Nancy.Serialization.JsonNet#59]
It would be good to add support for .NET Standard. Any plans for this?

**Comment by jchannon** [comment]
https://github.com/NancyFx/Nancy.Serialization.JsonNet/blob/master/src/Nancy.Serialization.JsonNet/project.json#L20

Already does. Nuget package will be coming soon

**Comment by cocowalla** [comment]
Sorry about that - after opening the issue I downloaded the project to have a crack at it myself... and only _then_ noticed the project.json file!

**Comment by jchannon** [comment]
:)
