### ISSUE TITLE
Lower-case keys after update to Nancy 0.22

### ISSUE THREAD

**Issue by igorkulman** [NancyFx/Nancy.Serialization.JsonNet#8]
I have updated Nancy from 0.21 to 0.22 and noticed a change that broke my server. All the JSON keys in JSON response (Response.AsJSON) changed to lower case. Is this a known issue or a bug? If it is not a bug, how to make it behave like before?

**Comment by cloud-garbage** [comment]
I'm relatively new to Nancy, and just stumbled upon this thread when I was trying to figure out why in the world the casing of my strings was being altered; in my case, stock symbols - ex: MSFT, AAPL, NVDA - were coming back as mSFT, aAPL, nVDA. the guy in [the issue](https://github.com/NancyFx/Nancy/issues/1362) @khellang linked to says that "99% of the time", this sort of automagic alteration is wanted. perhaps my use case (data that is explicitly all-caps) is in that 1%, but I'm still having trouble imagining why changing a method's return data AT ALL is a good default. does anyone have ideas about this? the workaround (using `Nancy.Json.JsonSettings.RetainCasing = true`) is easy enough to implement, so I'm not exactly complaining, but I do realize that the act of asking about this decision is implicitly a challenge of that decision. I also realize that I might just currently be trapped in my 1% use-case perspective, unable to see the larger picture; if someone could point me to that larger picture, that'd be cool :P
